### ISSUE TITLE
App stop working when click `Update` button

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#442] opened 2023-05-16 12:01 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.878.0 nightly

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10
```

### Issue Details

Steps to reproduce:
1. Click the `Update` button when the new update is available.

### Expected Behavior

When the new update is available and the `Update` button is clicked, the application shouldn't stop working and should work properly. I had this issue in the previous update and I uninstalled it with the [Advanced uninstallation](https://adguard-vpn.com/kb/adguard-vpn-for-windows/installation/#advanced) method, then I installed the latest nightly version on website. But the issue still persists when the new update is available.

### Actual Behavior

When a new update is available and I click the `Update` button, the application stops working.

### Screenshots

<details><summary>Screenshot 1:</summary>

https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/f2824c71-e1ff-4933-ae25-e57325a6076a
</details>

**Comment by AlexandrPkhm** [comment] 2023-05-19 07:31
@gork7777 Unfortunately, we were unable to reproduce the issue. To diagnose and troubleshoot it, we need to get the app logs.

Here's what we need you to do:

1. Go to Settings --> App settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will
need it to find the corresponding entries in the log file;
3. Open Support tab --> **Export logs and system info**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

**Comment by gork7777** [comment] 2023-05-20 00:33
@AlexandrPkhm Well, I can't reproduce it now, weird. If I can reproduce it, I'll send the archive.

**Comment by Batman2814** [comment] 2023-05-20 01:34
this happened to me when I was on Adguard for the Windows Nightly version. I had to uninstall Adguard VPN for Windows Nightly for me to get the latest update. I clicked update so many times it didn't do anything. Definitely an issue here.

**Comment by AlexandrPkhm** [comment] 2023-05-23 07:52
@Batman2814 In this case we will need the debug logs of the issue recorded and sent to us. Please also be sure to include the exact time at which the problem was reproduced. A video recording of the issue would also be extremely helpful. You can send the log archive and a video to devteam@adguard.com. Be sure to include this GitHub issue number in the subject.

**Comment by Batman2814** [comment] 2023-05-23 11:42
I'll have to wait for the next update for Adguard for Windows to get the debug logs because that's when it happens.

**Comment by AlexandrPkhm** [comment] 2023-06-26 11:49
Hi!

The issue has been closed as we have not been able to reproduce it. Please contact us if you encounter it again and we will continue to investigate.

**Closed by AlexandrPkhm** 2023-06-26 11:49 UTC
Labels: Bug, waiting for data

**Comment by Batman2814** [comment] 2023-06-26 12:13
It's working now.
