### ISSUE TITLE
Enabling "Use QUIC" Causes Websites to load forever casuing Internet to freeze

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForWindows#655] opened 2024-04-02 19:27 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.4

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11 23H2
- Other network-level software: Bitdefender Total Security (I Have AdGuard VPN for Windows under the Exclusions list in Bitdefender).
```

### Issue Details

Steps to reproduce:
1. Turn on QUIC in AdGuard VPN for Windows
2. Go into your browser to load or browse for a while eventually websites start to buffer and internet freezes.  
3.

### Expected Behavior

You should be able to surf the web in your browser without causing websites to load forever and internet freezes. You should be able to surf the web in your browser without causing websites to load forever, and the internet freezes.

### Actual Behavior

Internet Freezes causing websites to load forever with blank screen. Internet Freezes, causing websites to load forever with blank screens.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Batman2814** [comment] 2024-04-02 19:33
Logs have been sent

**Comment by AlexandrPkhm** [comment] 2024-04-24 15:49
@Batman2814 Hi,

Please accept our apologies for the delayed response. It seems that the issue you are encountering is related to DNS operation with QUIC enabled. This issue has been fixed in the recent VPN client update, which should be present in the latest nightly version of AdGuard VPN for Windows.

We have conducted our own testing and have not encountered any issues. Please download the latest version via this [link](https://agrd.io/windows_vpn_nightly) and check if the issue still persists on your end. Let us know of the results.

**Comment by Batman2814** [comment] 2024-04-27 01:02
The issue appears to have been resolved, as web pages are now loading without any problems.

**Comment by AlexandrPkhm** [comment] 2024-04-27 08:48
@Batman2814 

Thanks for letting us know! We are happy to hear that the issue is no longer present.

**Closed by AlexandrPkhm** 2024-04-27 08:48 UTC
Labels: Bug, Priority: P4
