### ISSUE TITLE
Subnet exclusions description is blinking

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#334] opened 2022-10-06 21:04 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  v2.0.664.0
- **VPN mode:**
  -  Local VPN
- **Operating system and version:**
  -  Windows 10
- **Other network-level software:**
  - 

### Expected Behavior

Subnet exclusions description should work like other description, shouldn't be blinking when you hovering the cursor.

### Actual Behavior

Subnet exclusions description is blinking when you hovering the cursor. It looks fine in English but it broken with other languages I guess.

### Screenshots

<details><summary>Screenshot:</summary>

https://user-images.githubusercontent.com/35523759/194417823-07a276ee-e546-4d90-9ef4-433a3b8e4ac2.mp4
</details>

**Comment by mozartinio** [comment] 2022-10-07 09:11
@gork7777 
Hello!
Did you try to reload the app? Asking because its not reproduce on our side
Also tried on 10/11 windows - everywhere works fine

**Comment by mozartinio** [comment] 2022-10-07 09:13
@gork7777  
Got this! 
Thank you!

**Comment by mozartinio** [comment] 2023-02-02 07:51
@gork7777 
Hello! 
There is no more reproduce and im going to close the issue
If you still have a problem you can reopen it

**Closed** 2023-02-02 07:52 UTC
Labels: Bug, Status: Resolved, Resolution: Fixed, Version: VPN v2.1, low
