### ISSUE TITLE
VPN doesn't start / open and Require Reinstall in every few days

### ISSUE THREAD

**Issue by Neeraj-aicreatives** [AdguardTeam/AdGuardVPNForWindows#545] opened 2023-10-09 11:15 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.7 (1030)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10
- Other network-level software: window defender
```

### Issue Details

Steps to reproduce:
1. I installed it the first time and everything works well, with no problems.
2. After a few days of using it, one day when I tried to open it it didn't open but processing in task manager.
3. I did everything but it didn't work then I reinstalled it and it worked but again after a few days, I'm facing the same problem.
4. I have tried it on multiple devices since I have 10 devices plan but having issues in every system.

### Expected Behavior

It should work every time when I open it, nobody has the time to reinstall every time and then log in.

### Actual Behavior

It never opens when I need it

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Aydinv13** [comment] 2023-10-10 15:11
@Neeraj-aicreatives Hi there!

1. Do you see only AdguardSvc.exe process in task manager?
>After a few days of using it, one day when I tried to open it it didn't open but processing in task manager.

2. You're using the app for a few days and what happens next? Are you rebooting your system or just closing VPN?

3. Are the devices you checked Windows PCs?
> I have tried it on multiple devices since I have 10 devices plan but having issues in every system.

Please check the latest [nightly](https://agrd.io/windows_nightly) build and let us know how it goes.
In case you face the same problem collect the debug logs:

<details>
<summary>Instruction</summary>

1. Go to Settings --> General --> App settings -->Advanced settings --> Logging level --> **Record everything**;
2. When the problem occurs remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to `%programdata%/adguardvpn`-> right click on Logs folder-> Send to-> Compressed folder;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
</details>

**Comment by Neeraj-aicreatives** [comment] 2023-10-17 06:56
We are unable to send the log files because the application won’t start, which is the issue we're trying to resolve. We would need to open the app to access and download the logs, but this isn't possible as the app won't open in the first place.

**Comment by Aydinv13** [comment] 2023-10-17 08:12
@Neeraj-aicreatives 

>We are unable to send the log files because the application won’t start, which is the issue we're trying to resolve.

That's why I asked to go directly to the logs folder on system (`%programdata%/adguardvpn`) after reproducing the problem.

**Comment by Aydinv13** [comment] 2023-10-23 09:09
@Neeraj-aicreatives any news?

**Comment by Neeraj-aicreatives** [comment] 2023-10-27 05:43
Here are the log files it stopped working on 18th October. I’ll have to re-install it again and again to use after every few days.

**Comment by Aydinv13** [comment] 2023-10-27 10:36
I'm sorry but there are no any logs/attachments on devteam@adguard.com. Could you please send it again.

**Comment by Neeraj-aicreatives** [comment] 2023-10-27 10:45
Attached the logs again.

**Comment by Aydinv13** [comment] 2023-10-31 13:10
@Neeraj-aicreatives 

Please, remove your current build via [advanced uninstaller](https://cdn.adtidy.org/distr/windows/Uninstall_Utility.zip) (`Unarchive -> Open Adguard.UninstallUtility.exe -> Choose Advanced uninstall + Delete AdGuard VPN -> Uninstall`. Follow the process) and try the newest [nightly](https://agrd.io/windows_vpn_nightly).

**Comment by Aydinv13** [comment] 2023-11-13 09:28
@Neeraj-aicreatives any update?

**Comment by Aydinv13** [comment] 2023-11-17 09:23
The issue has been closed due to no response. Can be opened again if still relevant.

**Closed by Aydinv13** 2023-11-17 09:23 UTC
Labels: Bug, waiting for data, Priority: P4
