### ISSUE TITLE
Memory leak in AdGuard VPN service

### ISSUE THREAD

**Issue by northis** [AdguardTeam/AdGuardVPNForWindows#579] opened 2023-12-01 14:47 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.1140

### Operating mode

None

### Environment

```markdown
Windows 10.0.19045
Ticket id 839335
```

### Issue Details

Steps to reproduce:
1. Happens at a random time, the service process consumes 4gb and terminates.

**Comment by enakr** [comment] 2023-12-19 13:06
New dump files, for version 2.2, in CRM 839335

**Comment by vankos** [comment] 2024-05-27 08:59
@enakr, hi! 
Could you please tell us if the issue reproduces on the latest versions?

**Comment by vankos** [comment] 2024-06-03 07:21
I will close it for now, since it is not reproducing on our side, but please feel free to reopen it if the issue recurs.

**Comment by vankos** [comment] 2024-06-03 07:34
I will close it for now, since it is not reproducing on our side, but please feel free to reopen it if the issue recurs.

**Closed by vankos** 2024-06-03 07:34 UTC
Labels: Bug, Status: In Progress, Priority: P4, Version: VPN v2.4
