### ISSUE TITLE
AdGuard DNS's DoQ server isn't available in AdGuard VPN

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdGuardVPNForWindows#414] opened 2023-03-01 13:10 UTC
@Batman2814 commented on [Tue Jan 31 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626)

when ever I have Adguard personal DNS protocol quic setup in Adgaurd for Windows I get a message pop up saying its not available. I know it says in the app experimental but this problem should be fix in the next update. when I use adgaurd personal DNS protocol TLS it works find. not sure if this belongs to Adguard DNS or Adgaurd VPN for windows or maybe both. 

---

@Chinaski1 commented on [Fri Feb 03 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1448355854)

Hello there!

It looks like QUIC upstream is unavailable for some reason
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/windows/solving-problems/adguard-logs).
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file.
3. Send the archive to `devteam@adguard.com` and mention this issue number in the subject.

---

@Batman2814 commented on [Fri Feb 03 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1448355863)

next time it happens I will get the logs. don't know when that will be.

---

@Batman2814 commented on [Mon Feb 27 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1448355869)

sent logs. let me know if I need to send another log file.

---

@Chinaski1 commented on [Tue Feb 28 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1448355875)

It would help if you tried to check on the latest version of the application

1. Update the AdGuard app to [Nightly version](agrd.io/windows_nightly)
2. Reset to default settings
3. Set AdGuard Private QUIC DNS as upstream
4. Turn on the debug log
5. Reproduce the issue. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file.
6. Send the archive to devteam@adguard.com and mention this issue number in the subject.

---

@Batman2814 commented on [Tue Feb 28 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1448371395)

Do you need me to send the logs again next time it happens or did I catch the issue in the last log file I sent when it was under Adgaurd DNS?

---

@Chinaski1 commented on [Tue Feb 28 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1448519832)

Send the logs again when it happens but on the Nightly version with debug log level

---

@Batman2814 commented on [Tue Feb 28 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1448528627)

Do I install the Adguard VPN for Windows Nightly version to or just Adguard for Windows Nightly?

---

@Aydinv13 commented on [Wed Mar 01 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1449959497)

@Batman2814 Hi there!

It's not quite clear which product you mean right now. Is it **AdGuard VPN for Windows** or **AdGuard For Windows** (ad blocker)? Judging from the logs you sent it's AdGuard (ad blocker), but you mentioned AdGuard VPN (e.g. in title)

---

@Batman2814 commented on [Wed Mar 01 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4626#issuecomment-1450050096)

It's Adguard VPN for Windows that is having the problem when adgaurd private DNS is set up in Adgaurd VPN for Windows using protocol QUIC.

**Comment by Aydinv13** [comment] 2023-03-01 13:28
@Batman2814 I wasn't able to reproduce this problem so could you please collect debug logs in AdGuard VPN:
Here's what we need you to do:
1. Go to Settings --> General --> App settings -->Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to Support -> **Export logs and system info**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

**Comment by Batman2814** [comment] 2023-03-01 13:50
K I will send it next time it happens.

**Comment by Batman2814** [comment] 2023-03-06 16:31
Just letting you know that I'm still waiting for the problem to be reproduced to collect the logs.

**Comment by mozartinio** [comment] 2023-03-17 07:06
@Batman2814 
Any news?

**Comment by Batman2814** [comment] 2023-03-17 15:04
The bug hasn't shown up for me yet. I'm still waiting, but like before, the problem was happening rarely, so it could be hard to catch.

**Comment by mozartinio** [comment] 2023-03-22 09:52
@Batman2814 we are looking for the cause of the problem
Thank you for your logs!

**Comment by VladisLoveZh** [comment] 2023-05-11 08:10
@Batman2814 

Please download beta or Nightly version of the app to see if that helps

https://agrd.io/windows_vpn_beta 
https://agrd.io/windows_vpn_nightly 

Also, what if you set DNS to default\system? 
Can you reproduce the issue using different servers\locations as well?

**Comment by AlexandrPkhm** [comment] 2023-05-15 10:24
@Batman2814 

Please let us know if there are any news.

**Comment by AlexandrPkhm** [comment] 2023-05-23 10:23
@Batman2814 Hi! 

We are closing this issue due to lack of information. If you encounter it again, please contact us and we'll continue to investigate.

**Comment by Batman2814** [comment] 2023-05-24 16:13
I sent logs to you guys where I was able to reproduce it. If you can reopen the GitHub issue report, please?

**Comment by AlexandrPkhm** [comment] 2023-05-25 06:31
@Batman2814 Hi! 

As we can see from the logs you are using AdGuard VPN for Windows 2.0.7. Please download beta or Nightly version using the following links:
https://agrd.io/windows_vpn_beta
https://agrd.io/windows_vpn_nightly

Let us know if the issue is reproduced on this version.

**Comment by Batman2814** [comment] 2023-05-25 16:58
Just Installed the beta version of Adguard VPN for Windows. I will have to monitor it to see if the problem is reproduced in this beta version.

**Comment by Batman2814** [comment] 2023-05-26 14:42
logs have been sent for the beta Version where it was also happening on the beta version just like on the Release version.

**Comment by Batman2814** [comment] 2023-05-30 20:58
This is just to confirm that it's happening in the Nightly Version of AdGuard VPN for Windows.

**Comment by VladisLoveZh** [comment] 2023-06-29 09:40
@Batman2814 
Hi, 

Previous logs were somehow cut in half.
Would you please update your AdGuard VPN to the latest Nightly 2.1? https://agrd.io/windows_vpn_nightly

And then record TRACE logs as described below:
1.Stop AdGuard VPN. Please don't leave the service running, and make sure that there's no process of it running in Task Manager
2.Open the command line (type 'cmd' in the start panel).
3.Run the app with the command C:\Progra~2\AdguardVpn\AdguardVpn.exe /debug /trace
4.Reproduce the issue. 
5.Go to %programdata%\AdguardVpn\Logs compress the logs and send them over, don't forget about a timestamp when the issue happened.


/

**Comment by Batman2814** [comment] 2023-07-01 00:27
This is an update saying I try this, but it has to be later when I have time. So keep this issue open for the time been.

**Comment by Batman2814** [comment] 2023-07-09 21:31
This is an update that I'm going to try to reproduce it. I already installed AdGuard VPN Nightly for Windows, so when it's reproduced, I'll send it to the AdGuard email that you guys posted.

**Comment by Batman2814** [comment] 2023-07-09 22:28
Logs have been sent.

**Comment by Batman2814** [comment] 2023-10-25 17:17
When you say the latest version, do you mean the Stable release version of AdGuard VPN for Windows, which is Version 2.1.10?

**Comment by AlexandrPkhm** [comment] 2023-10-25 18:59
@Batman2814 

Yes, indeed. The version 2.1.10.

**Comment by Batman2814** [comment] 2023-10-25 19:42
So Far, it is good. I have yet to see it pop up.

**Comment by AlexandrPkhm** [comment] 2023-10-25 20:55
@Batman2814 

We are happy to hear that the issue has been resolved. We will close it for now. If you encounter this issue again, please let us know and we'll continue to investigate.

**Closed by AlexandrPkhm** 2023-10-25 20:55 UTC
Labels: Bug, waiting for data, Priority: P4
