### ISSUE TITLE
DNS not bypassed when using vpn

### ISSUE THREAD

**Issue by TommyKing** [AdguardTeam/AdGuardVPNForWindows#42] opened 2020-12-20 15:32 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Y] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  0.0.117.0
- **VPN mode:**
  VPN mode
- **Operating system and version:**
  Windows 10 Enterprise LTSC
- **Other network-level software:**
  - Adguard, Eset Internet Security with firewall disabled.

### Expected Behavior
it should by using vpn's dns server. as vpn routing all connection

### Actual Behavior

Windows still use DNS on adapter settings in network and sharing

### Screenshots

![Capture](https://user-images.githubusercontent.com/6888937/102717269-ce544180-4313-11eb-82ee-c34417c50291.PNG)

### Additional Information

see the screenshot applicable it did not bypass my ISP internet blocking. usually DNS with different port or encrypted dns or vpn should always bypassed it.

i use Unbound for local recursive and when i use unbound. i don't have any connection when adguard vpn is on

**Comment by adbuker** [comment] 2020-12-21 13:39
@TommyKing, the root of the issue in the opened (to be more accurate - "no closed") connection(s), which was(were) opened before all the traffic was tunneled via VPN. In other words, DNS resolve was extracted from the so-called cache. Unfortunately, as of now, AdGuard VPN hasn't a "kill connection" feature, but we are going to do it.  To reach the same effect you can close the browser or e.g. close all the connections manually, clicking both buttons on the chrome://net-internals/#sockets

**Comment by ameshkov** [comment] 2020-12-21 14:11
@adbuker can't we add "tcpkill" option just like we do in AG?

**Comment by adbuker** [comment] 2020-12-21 14:38
@ameshkov , yes of course, we'll do it.

**Comment by TommyKing** [comment] 2020-12-22 03:37
@adbuker if this is the case, why in my adg home query log there's vpn ip logged there after 30s no activity?
![20201222_103436](https://user-images.githubusercontent.com/6888937/102845976-5edc7000-4441-11eb-909c-8451dce348ba.jpg)

Shouldn't it use vpn's dns?  And also sometimes when on i have no connection ( when i use unbound as dns in windows  )

**Comment by adbuker** [comment] 2021-01-11 10:11
@TommyKing , these are DNS requests to our injection server only. On the core-level, we intercept them ourselves and get the response, without resolving DNS addresses (`injections.adguard.org`) "in good faith" in fact. In that meaning, they are not real DNS requests, but the query log continues to show them as a DNS resolved via system DNS server without tunneling. To be shorter, you mustn't worry about any kinda leak or smth else

**Comment by ameshkov** [comment] 2021-01-11 10:16
DNS queries that are being sent by AdGuard itself should also go to the tunnel, this is a legit issue.

**Comment by ameshkov** [comment] 2021-01-11 10:26
Btw, `193.56.255.114` from the screenshot is an IP address of our VPN server so it was actually routed to our VPN.

The question is why the query ended up in AGH and not in the DNS server configured in AG VPN.

**Comment by adbuker** [comment] 2021-01-11 10:56
@TommyKing , could you please enable AdGuard VPN debug [logging level](https://uploads.adguard.com/buker-zcu9l.png) (along with the AdGuard [logging level](https://kb.adguard.com/en/windows/solving-problems/adguard-logs)), repro the issue, grab the collected logs (from [AdGuard VPN](https://uploads.adguard.com/buker-5zyrw.png) and [AdGuard](https://kb.adguard.com/en/windows/solving-problems/adguard-logs)) and send it to dev-team@adguard.com with subject "logs for issue 42".

**Comment by TommyKing** [comment] 2021-01-11 19:02
@adbuker let me try...i'll sent it when it does occured

**Comment by TommyKing** [comment] 2021-01-12 02:37
ok got it. @adbuker sent the logs to dev-tem@adguard.com. please check it. let me know if you want anything else

**Comment by adbuker** [comment] 2021-01-25 14:03
The issue happens only if the DNS port, which differs from the default 53, is used. Nevertheless, we can recognize DNS traffic among the other ones without binding to a certain port, but we have to work on it. This new approach will be implemented further

**Comment by ngorskikh** [comment] 2021-01-25 14:40
@TommyKing Hi! Let me explain what's happening:

1. AdGuard VPN intercepts network traffic to port `53`, which is the standard DNS port, and redirects it through our VPN endpoint to a secure DNS provider.
2. You've convinced your system resolver to, instead, use a custom DNS server address with a non-standard port.
3. As a result, your system's DNS queries go through our endpoint to your custom DNS server. 

Solution: disable your custom DNS address:port trickery :) Do not worry about DNS queries leaking to your ISP: AdGuard VPN intercepts network traffic before it leaves your machine, and works transparently (meaning that your apps will still "think" they're using your ISP's DNS settings). You can use various online DNS leak checks to make sure that your ISP is not seeing your DNS queries.

As per your initial problem illustrated by the screenshot, it was most probably caused by your browser reusing a connection already established while AdGuard VPN was offline. This is a known issue and we are working on an already-established-connections-termination function.

**Comment by ameshkov** [comment] 2021-01-26 09:37
@ngorskikh we should file a new issue about that - allow detecting DNS traffic on the driver level (without passing it to the user mode). It's not urgent, but it'd nice to have.

**Closed** 2022-06-21 12:01 UTC
Labels: Resolution: Done, Status: Resolved, feature request, Version: VPN v1.3
