### ISSUE TITLE
AG VPN app and service unresponsive after system start

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardVPNForWindows#183] opened 2021-11-23 11:07 UTC
### Issue Details

- **AdGuard VPN version:**
  -  1.1.366
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - Windows 10 Pro 21H2 OS Build 19044.1348
- **Other network-level software:**
  - AdGuard for Windows 7.7.2, Windows Security

### Expected Behavior

AG VPN for Windows to work

### Actual Behavior

On system boot, AG VPN for Windows appears to be working however clicking system tray icon only opens sub menu, but it is unresponsive (see screenshot). Attempts to open app UI fail. Attempts to Stop the AG VPN service also fail with service hanging in a Stopping state.

### Screenshots

![2021-11-23_22-00-23](https://user-images.githubusercontent.com/17214552/143013377-9c31ba1d-a0af-42f9-af74-16d35c619934.jpg)

### Additional Information

This was a clean install, not an upgrade.
Tried multiple reboots but always same result.
No errors in System or application event log

**Comment by Aydinv13** [comment] 2021-11-23 12:36
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Go to Settings --> General --> Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will need it to find the corresponding entries in the log file;
3. Go to Settings -> General -> **Export logs**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

**Comment by AnthonyBe** [comment] 2021-11-24 09:24
As I mentioned in my original post, I can't access the UI.
The UI becomes completely unresponsive so I cannot change logging levels nor export logs.
The UI is unresponsive right from boot.

Is there a way for me to change the logging level and get the log files _without_ using the UI?

**Comment by Aydinv13** [comment] 2021-11-24 12:47
Ok then go to `C:\ProgramData\AdguardVpn` and send `Logs` folder to us please

**Comment by DeepBlue235** [comment] 2021-11-26 22:55
Same issue here. Fresh install is working, but after reboot UI stops responding. VPN connection is working, though. Try to send you some logs, too.

**Comment by Aydinv13** [comment] 2021-11-29 09:45
@AnthonyBe @DeepBlue235 Could you check it on the [latest nightly](https://agrd.io/windows_vpn_nightly) version?

**Comment by DeepBlue235** [comment] 2021-11-29 20:10
Latest nightly has the same issue.

**Comment by Aydinv13** [comment] 2021-11-30 09:03
@DeepBlue235  Received thanks. We'll investigate the issue

**Comment by Aydinv13** [comment] 2021-11-30 09:36
@DeepBlue235 Sorry, but your logs show version 1.1.366.0, which is the release version. Could you please install nightly build from the link above?

**Comment by DeepBlue235** [comment] 2021-11-30 10:40
@AnthonyBe The logs are from the release version, right. But I tried the nightly on 26th november and yesterday, too. Results are the same.

**Comment by Aydinv13** [comment] 2021-11-30 10:48
@DeepBlue235 nevertheless could you provide us with recent logs? Thank you

**Comment by DeepBlue235** [comment] 2021-11-30 21:52
@Aydinv13 New logs send.

**Comment by northis** [comment] 2021-12-14 12:21
@DeepBlue235 Thank you for logs. Unfortunately, we cannot reproduce this issue. However, you can reproduce the problem, create dump file of AdGuardVpn.exe process and send us the file:
https://uploads.adguard.com/win-northhu3jz.png
https://uploads.adguard.com/win-northr8lu4.png
To save the traffic, zip this file before sending.

**Comment by DeepBlue235** [comment] 2021-12-20 07:10
Will report back later this week

**Comment by DeepBlue235** [comment] 2021-12-28 11:23
The good news is, i installed the new nightly today and wasn't able to reproduce the main issue anymore (UI is responsive). Didn't used Adguard VPN for last two weeks though.
But now i am not able to close Adguard VPN or dis- and reconnect anymore until I restart the system. I have to re-login after a restart and it is working fine until new restart. Afterwards a disconnect or closing is not possible. Reported through the UI, send you a dump, too.

**Comment by northis** [comment] 2022-01-10 16:33
@DeepBlue235 Thank you for the dump files you've sent, we will fix the issue in one of the next releases.

**Comment by northis** [comment] 2022-01-13 08:16
@DeepBlue235 Please, try the latest nightly version (1.2 nightly 9). The problem may be solved in this version.

**Comment by Aydinv13** [comment] 2022-01-17 17:53
Closed due to no reply. You can reopen this issue anytime.

**Closed by Aydinv13** 2022-01-17 17:53 UTC
Labels: Status: Resolved, Resolution: Cannot Reproduce, P3: Medium, Version: VPN v1.2
